### PR TITLE
S3FileStore & more

### PR DESCRIPTION
**Pull request by sbeimin**
This branch adds:
- FileStore support
- configurable AmazonS3Factory support (for injecting custom S3 client's)
- fully customizable AmazonS3Client configuration options (via environment variables, System properties, amazon.properties file or a directly provided java.util.Map<String, ?>)
- AmazonS3Client RequestMetricCollector support
- Multiple S3FileSystem support

with 100% UnitTest Line Coverage (and 95% Branch Coverage according to cobertura).

### CODE REVIEW

**Comment by jarnaiz** [comment]
Hello again :)

Now I'm working on S3FileStore class and after reviewing the code I think I'm going to move the logic of this class to S3FileSystemProvider class in the same way as the changes I've made in the S3Path class (not pushed yet). I think that in this way the original idea of the FileStore, and FileSystemProvider Path class is better respected and I can remove some dependencies between these classes.
The S3FileSystemProvider class will grow a little because it will contain all the S3 operations but I will try to create some subclasses to group operations and also part of this work you've already done with Walker, S3Iterator, S3Seekable and other classes.

Because Its not a lot of work, when I finished it we can discuss and see what code is cleaner and clearer.

Regards and any suggestion or warning, please let me know.

**Comment by sbeimin** [comment]
Hello Javier,

The reason for putting most of the S3 interaction code into the S3FileStore is described by the following line from the java.nio.file.FileStore API comments: 
> Storage for files. A FileStore represents a storage pool, device, partition, volume, concrete file system or other implementation specific means of file storage.

Where the the java.nio.file.FileSystem 
> Provides an interface to a file system and is the factory for objects to access files and other objects in the file system.

In my mind a class should do what it's name describes. So a S3FileSystemProvider should do exactly that: Provide S3FileSystems. From java.nio.file.spi.FileSystemProvider:
> A provider is a factory for one or more FileSystem instances.

That's why I delegated the implementation of the abstract methods defined by java.nio.file.spi.FileSystemProvider down to the other classes like S3FileStore, S3Walker, S3Iterator and S3Seekable

**Comment by jarnaiz** [comment]
Hi @sbeimin 

Im sorry for my late reply but at last I have finished my refactor for your branch.

I refactored S3FileStore to only be the representation of a bucket, eliminating most of logic and only using AmazonS3Client for the interface mandatory operations as:

* getFileStoreAttributeView
* getAttribute

Regarding the responsibility of FileSystemProvider, I understand your argument but I think FileSystemProvider is not just a factory because its interface requires the implementation of the logic of access to files, create input streams and others.

So I've moved most of the use of AmazonS3Client to S3FileSystemProvider and thus have reduced the coupling between S3FileStore and others classes.

I created S3Utils to group related operations between S3Path and Amazon objects like ObjectListing and others.

In any case, it is best that you check the code and tell me what you think.

greeting and thanks for everything!

**Comment by jarnaiz** [comment]
Hi @sbeimin 

I recently upload to maven central the new version 1.0.0-SNAPSHOT.

Thanks for everything, this version has certainly been through all the work you've done. I hope the result seems good.

And of course, this is a work in progress, so I hope we can continue working ;)

cheers!

**Pull request merged**
